### ISSUE TITLE
No Sidebar area

### ISSUE THREAD

**Issue by samgreco** [backdrop-contrib/two_column_flexible#3]
I've installed the Two Column Flexible layout.  But when I go to add a block to the sidebar, there is no sidebar area.  I see a sidebar region in Moscone and others.  But not in this layout.

Is there some setup somewhere I'm missing?

**Comment by docwilmot** [comment]
Youre right; dont know why that is. If you flush caches it might show up again. But the themeing of this layout needs work; there's been a lot of changes in Backdrop since it was last touched. Thanks for reporting.

**Comment by docwilmot** [comment]
seems this is a core issue. if you install a new layout, you must flush caches otherwise Backdrop actually doesnt render the new template.
https://github.com/backdrop/backdrop-issues/issues/3665
